version: '3.7'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    network_mode: bridge
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: itis1sem
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: alena
      MYSQL_PASSWORD: verystr0ngp4ssw0rd
